# Generated by Django 5.2.6 on 2025-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in use ', 'In Use'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20),
        ),
    ]
