# Generated by Django 5.2.6 on 2025-09-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackpoint', '0002_staff_email_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
