# Generated by Django 5.2.6 on 2025-10-02 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackpoint', '0005_alter_asset_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
